name: Install Nginx

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Nginx on Server
        run: |
          sshpass -p "${{secrets.REMOTE_PASSWORD}}" ssh -o StrictHostKeyChecking=no ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}} 'sudo apt-get update && sudo apt-get install -y nginx'
