name: SSH Connect and Create File
on:
  push:
      branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Remote machine & Create file
        run: |
            sshpass -p "${{secrets.REMOTE_PASSWORD}}" ssh -o StrictHostKeyChecking=no ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}} << EQF
            echo "FIle created successfully" > /home/ai/test.txt
            EQF
